[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "xmltojson"
author = "Diggory Blake"
author-email = "diggsey@googlemail.com"
classifiers = ["License :: OSI Approved :: MIT License"]

